-- Enable PostGIS extension for spatial queries
CREATE EXTENSION IF NOT EXISTS postgis;

-- Amenities reference table
CREATE TABLE amenities (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Users table
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT auth.uid(),
  email TEXT UNIQUE NOT NULL,
  first_name TEXT,
  last_name TEXT,
  avatar_url TEXT,
  preferences JSONB DEFAULT '{"notifications": {"travel_alerts": true, "booking_reminders": true, "promotions": false}, "theme": "automatic"}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Gym owners table
CREATE TABLE gym_owners (
  id UUID PRIMARY KEY DEFAULT auth.uid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  gym_name TEXT NOT NULL,
  stripe_account_id TEXT,
  stripe_onboarding_complete BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Gyms table
CREATE TABLE gyms (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  owner_id UUID NOT NULL REFERENCES gym_owners(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  country TEXT NOT NULL,
  latitude DECIMAL(10, 8) NOT NULL,
  longitude DECIMAL(11, 8) NOT NULL,
  location GEOMETRY(POINT, 4326) GENERATED ALWAYS AS (
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
  ) STORED,
  phone TEXT,
  website TEXT,
  rating DECIMAL(3, 2) DEFAULT 0,
  review_count INTEGER DEFAULT 0,
  day_pass_price DECIMAL(10, 2),
  week_pass_price DECIMAL(10, 2),
  month_pass_price DECIMAL(10, 2),
  google_place_id TEXT UNIQUE,
  is_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create spatial index
CREATE INDEX gyms_location_idx ON gyms USING GIST(location);

-- Gym amenities junction table
CREATE TABLE gym_amenities (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  gym_id BIGINT NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  amenity_id BIGINT NOT NULL REFERENCES amenities(id) ON DELETE CASCADE,
  is_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(gym_id, amenity_id)
);

-- Gym hours table
CREATE TABLE gym_hours (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  gym_id BIGINT NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  opens_at TIME,
  closes_at TIME,
  is_closed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(gym_id, day_of_week)
);

-- Gym photos table
CREATE TABLE gym_photos (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  gym_id BIGINT NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Bookings table
CREATE TABLE bookings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  gym_id BIGINT NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  booking_date DATE NOT NULL,
  pass_type TEXT NOT NULL CHECK (pass_type IN ('day', 'week', 'month')),
  status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'used', 'cancelled')),
  amount_paid DECIMAL(10, 2) NOT NULL,
  platform_fee DECIMAL(10, 2) NOT NULL,
  gym_payout DECIMAL(10, 2) NOT NULL,
  stripe_payment_intent_id TEXT,
  qr_code JSONB,
  qr_scanned_at TIMESTAMP WITH TIME ZONE,
  qr_scanned_by UUID,
  waiver_signed BOOLEAN DEFAULT FALSE,
  waiver_signed_at TIMESTAMP WITH TIME ZONE,
  waiver_ip_address TEXT,
  waiver_version TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Reviews table
CREATE TABLE reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  gym_id BIGINT NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  booking_id BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  helpful_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Travel periods (detected trips) table
CREATE TABLE travel_periods (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  destination_city TEXT NOT NULL,
  destination_state TEXT,
  destination_country TEXT NOT NULL,
  destination_lat DECIMAL(10, 8) NOT NULL,
  destination_lng DECIMAL(11, 8) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  confidence_score DECIMAL(3, 2),
  source TEXT NOT NULL CHECK (source IN ('ios_calendar', 'google_calendar', 'manual')),
  source_event_id TEXT,
  dismissed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Voice queries table (for analytics and model improvement)
CREATE TABLE voice_queries (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transcript TEXT NOT NULL,
  parsed_intent JSONB,
  results_count INTEGER,
  selected_gym_id BIGINT REFERENCES gyms(id),
  transcription_method TEXT CHECK (transcription_method IN ('on_device', 'whisper')),
  processing_time_ms INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Saved gyms (favorites) table
CREATE TABLE saved_gyms (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  gym_id BIGINT NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, gym_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE gyms ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_amenities ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_hours ENABLE ROW LEVEL SECURITY;
ALTER TABLE gym_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE travel_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE voice_queries ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_gyms ENABLE ROW LEVEL SECURITY;

-- RLS Policies for users table
CREATE POLICY "Users can view their own profile"
  ON users FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile"
  ON users FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- RLS Policies for gyms (public read)
CREATE POLICY "Gyms are publicly readable"
  ON gyms FOR SELECT
  USING (true);

CREATE POLICY "Gym owners can update their own gyms"
  ON gyms FOR UPDATE
  USING (owner_id = (SELECT id FROM gym_owners WHERE user_id = auth.uid()))
  WITH CHECK (owner_id = (SELECT id FROM gym_owners WHERE user_id = auth.uid()));

-- RLS Policies for bookings
CREATE POLICY "Users can view their own bookings"
  ON bookings FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create bookings"
  ON bookings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own bookings"
  ON bookings FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- RLS Policies for saved_gyms
CREATE POLICY "Users can view their own saved gyms"
  ON saved_gyms FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can add to saved gyms"
  ON saved_gyms FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can remove from saved gyms"
  ON saved_gyms FOR DELETE
  USING (auth.uid() = user_id);

-- RLS Policies for travel_periods
CREATE POLICY "Users can view their own travel periods"
  ON travel_periods FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create travel periods"
  ON travel_periods FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own travel periods"
  ON travel_periods FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- RLS Policies for voice_queries
CREATE POLICY "Users can view their own voice queries"
  ON voice_queries FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can log voice queries"
  ON voice_queries FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Seed amenities
INSERT INTO amenities (name, icon) VALUES
('Weights', '🏋️'),
('Cardio', '🏃'),
('Classes', '👥'),
('Sauna', '🧖'),
('Pool', '🏊'),
('Yoga', '🧘'),
('CrossFit', '💪'),
('Boxing', '🥊'),
('Cycling', '🚴'),
('24 Hour', '⏰'),
('WiFi', '📡'),
('Lockers', '🔒'),
('Shower', '🚿'),
('Towel Service', '🛁'),
('Personal Training', '💬');
