-- Migration: Add sent_alerts table for tracking notification deduplication
-- This prevents sending duplicate travel alerts for the same trip

CREATE TABLE IF NOT EXISTS sent_alerts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  alert_key TEXT NOT NULL,
  alert_type TEXT NOT NULL CHECK (alert_type IN ('travel_alert', 'booking_reminder', 'promo')),
  sent_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  
  -- Prevent duplicate alerts
  UNIQUE(user_id, alert_key)
);

-- Index for quick lookups
CREATE INDEX IF NOT EXISTS sent_alerts_user_id_idx ON sent_alerts(user_id);
CREATE INDEX IF NOT EXISTS sent_alerts_alert_key_idx ON sent_alerts(alert_key);

-- RLS policies
ALTER TABLE sent_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own sent alerts"
  ON sent_alerts FOR SELECT
  USING (user_id = auth.uid());

CREATE POLICY "System can insert sent alerts"
  ON sent_alerts FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Clean up old alerts after 90 days to prevent table bloat
-- This can be run as a scheduled job
CREATE OR REPLACE FUNCTION cleanup_old_sent_alerts()
RETURNS void AS $$
BEGIN
  DELETE FROM sent_alerts WHERE sent_at < NOW() - INTERVAL '90 days';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

